### ISSUE TITLE
foo: bar is not removed (session storage test)

### ISSUE THREAD

**Issue by arnemahl** [unshiftio/sessionstorage#5]
In [index.js](https://github.com/unshiftio/sessionstorage/blob/a9d4f7ad9ea644bf9271f80da45fba2013fc88a8/index.js#L7) there is a test to write `foo: bar` to sessionStorage, and if it works it should be removed. However, `foo: bar` continues to exist in sessionStorage.

* How to reproduce: Just import this package in a web project, build it and open it in a browser (I used chrome)
* Observed behaviour: `foo: bar` exists in sessionStorage
* Expected behaviour: `foo: bar` should be removed immediately after it's added

The code is very straight forward, so I can not understand how this bug can appear, but it does (and it does not appear when I don't include this package).

**Comment by 3rd-Eden** [comment]
That.. Is really strange.

**Comment by Irazall** [comment]
I got the same "error"... looking forward to see this fixed :)

**Comment by Irazall** [comment]
I think I found the error: The node module is not installed correctly!
When I looked in my node modules folder in sessionstorage/index.js the following line was missing (also it is included in [index.js](https://github.com/unshiftio/sessionstorage/blob/a9d4f7ad9ea644bf9271f80da45fba2013fc88a8/index.js#L7) in the repository)

`sessionStorage.removeItem('foo');`

So, the solution would be to make a new release, e.g. 0.0.2 ;)

**Comment by lpinca** [comment]
Correct, this fix f7849ab1de520add24e2b41a0b8523f7bcffa39b has not been released.

**Comment by Irazall** [comment]
So, can anyone publish this release?^^

**Comment by lpinca** [comment]
yup @3rd-Eden :)

**Comment by 3rd-Eden** [comment]
Wow.. I can't believe I missed that lol. Published 0.0.2
